# EN LICENSE: YOU CAN'T USE THIS CODE FOR COMMERCIAL USE OR FOR COMMERCIAL PURPOSE, YOU CAN ONLY USE THIS WITHOUT ANY CODE MODIFICATION!!!
# PL LICENCJA: NIE MOŻNA UŻYWAĆ TEGO KODU DO CELÓW KOMERCYJNYCH LUB DO UŻYCIA KOMERCYJNEGO, MOŻNA UŻYWAĆ TYLKO BEZ ŻADNYCH MODYFIKACJI KODU!!!

