TOMBSTONE_BANTIME: 60.0
SWORD_EFFECT_AMF: 1
SWORD_EFFECT_TIME: 69
PICKAXE33_ENABLED: true
TOMBSTONE_ENABLED: true
STAT_S1_MAX: 200
STAT_S2_MAX: 200
STAT_S3_MAX: 200
STAT_S1_BAN: true
STAT_S2_BAN: true
STAT_S3_BAN: true
STAT_S1_START: 200
STAT_S2_START: 200
STAT_S3_START: 200
STAT_S1_RESTORE: 100
STAT_S2_RESTORE: 100
STAT_S3_RESTORE: 100
ITEM_MYSTERY:
  ==: org.bukkit.inventory.ItemStack
  v: 3105
  type: BOOK
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: '{"extra":[{"bold":true,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"MYSTERY
      BOOK"}],"text":""}'
    lore:
    - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"green","text":"JAKIES
      LORE #1"}],"text":""}'
    - '{"extra":[{"bold":false,"italic":false,"underlined":false,"strikethrough":false,"obfuscated":false,"color":"aqua","text":"JAKIES
      LORE #2"}],"text":""}'
